apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivemq-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivemq-broker
  template:
    metadata:
      labels:
        app: hivemq-broker
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: hivemq-broker
          image: ghcr.io/chrisvfabio/kubernetes-bare-metal/hivemq-broker:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.25"
              memory: "0.5Gi"
            requests:
              cpu: "0.25"
              memory: "0.5Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: hivemq-broker
spec:
  selector:
    app: hivemq-broker
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883