apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivemq-listener-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivemq-listener-node
  template:
    metadata:
      labels:
        app: hivemq-listener-node
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: hivemq-listener-node
          image: ghcr.io/<USERNAME>/<NAMESPACE>/hivemq-listener-node:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.25"
              memory: "0.5Gi"
            requests:
              cpu: "0.25"
              memory: "0.5Gi"
          env:
            - name: HIVEMQ_BROKER_HOSTNAME
              value: hivemq-broker.default.svc.cluster.local
            - name: HIVEMQ_BROKER_TOPIC
              value: test
            - name: MONGO_HOSTNAME
              value: mongodb.default.svc.cluster.local
            - name: MONGO_USER
              value: hivemq-listener